### ISSUE TITLE
User Story 1: Click movement

### ISSUE THREAD

**Issue by Mistake91** [Mistake91/capstone-project#1]
## Value Proposition

**As a User**  
**I want to move my character** 
**so that my character can be assigned to a work station**  

## Description

![US1](https://user-images.githubusercontent.com/117996219/213422725-e287e693-cf2e-4f2d-aaa3-39ac68f3b25d.png)

## Acceptance Criteria

- [x] character placeholder is displayed
- [x] three work stations are displayed
- [x] every work station is clickable
- [x] when clicking a work station, character should move to that station

## Tasks

- [x] create 3 buttons(workstations)
- [x] create a image as character placeholder
- [x] onClick function to change image position

## Complexity

S

**Comment by mbosselmann** [comment]
Hi Leif,
we love your description! Especially the dwarf. ;) We have some remarks for the other parts of your user story:

**Value proposition**
- We have a proposal for a better description of your feature with the focus on the goal and the customer:
As a User
I want to move my character
so that my character can be assigned to a work station

**Acceptance criteria**
- "3 workingstations with onClick" better would be:
- "three work stations are displayed"
- "every work station is clickable"
- "when clicking a **work station**, character should **move** to that station"

If you have questions, feel free to ask us! After editing your user story, please post the user story again in our thread. :)

**Comment by shebtastic** [comment]
Hey Leif,

great work and thanks for updating! :octocat:

Happy hacking! 🚀
