### ISSUE TITLE
User Story 6: mining coal

### ISSUE THREAD

**Issue by Mistake91** [Mistake91/capstone-project#10]
## Value Proposition

**As a User**
**I want to be able to mine coal**
**so that i can expand my amount of coal**

## Description

![US6](https://user-images.githubusercontent.com/117996219/214312626-013b5a31-f546-4702-ab06-be0f107427d7.png)

## Acceptance Criteria

- [x] amount of coal is global displayed
- [x] when character is moved to a deposit, the character start "working"
- [x] when character is "working" a "stop working" button is displayed
- [x] when "stop working" button is clicked, character stop working and go back to start position
- [x] 1 coal should be mined every 5 seconds
- [x] amount of coal should be stored in local-storage

## Tasks

- [x] import local-storage
- [x] create working function that count +1 every 5 seconds
- [x] create button that stop working function and change character position
- [x] create coal counter const that stored in local-storage
- [x] create li item that display coal counter

## Complexity

L

**Comment by RobinWitt** [comment]
Sounds well thought out and has good complexity and description. Approved!
