### ISSUE TITLE
User Story 7: mining iron

### ISSUE THREAD

**Issue by Mistake91** [Mistake91/capstone-project#12]
## Value Proposition

**As a User**
**I want to be able to mine iron**
**so that i can expand my amount of iron**

## Description

![US7](https://user-images.githubusercontent.com/117996219/214815138-c4e5e09e-dcf9-465f-93f1-f8167988b066.png)

## Acceptance Criteria

- [x] amount of iron is global displayed
- [x] when character is moved to a deposit, the character start "working"
- [x] when character is "working" a "stop working" button is displayed
- [x] when "stop working" button is clicked, character stop working and go back to start position
- [x] 1 iron should be mined every 5 seconds 
- [x] amount of iron should be stored in local-storage 

## Tasks

- [x] create working function that count +1 every 5 seconds
- [x] create button that stop working function and change character position
- [x] create iron counter const that stored in local-storage  
- [x] create li item that display iron counter 

## Complexity

S

**Comment by niklasrammelkamp** [comment]
nice ! 🥳
