### ISSUE TITLE
User Story 8: mining gold

### ISSUE THREAD

**Issue by Mistake91** [Mistake91/capstone-project#13]
## Value Proposition

**As a User**
**I want to be able to mine gold**
**so that i can expand my amount of gold**

## Description

![US(](https://user-images.githubusercontent.com/117996219/214815861-322209f6-2eb3-4773-900a-37e31ff422a3.png)

## Acceptance Criteria

- [x] amount of gold is global displayed
- [x] when character is moved to a deposit, the character start "working"
- [x] when character is "working" a "stop working" button is displayed
- [x] when "stop working" button is clicked, character stop working and go back to start position
- [x] 1 gold should be mined every 5 seconds
- [x] amount of gold should be stored in local-storage

## Tasks

- [x] create working function that count +1 every 5 seconds
- [x] create button that stop working function and change character position
- [x] create gold counter const that stored in local-storage
- [x] create li item that display gold counter

## Complexity

S
