### ISSUE TITLE
User Story 9: achievement system

### ISSUE THREAD

**Issue by Mistake91** [Mistake91/capstone-project#15]
## Value Proposition

**As a User**
**I want to have a achievement system** 
**so that i can see all achievements**

## Description

![US9](https://user-images.githubusercontent.com/117996219/214860946-f5b9cec2-e6d7-426e-982e-f7d1c9cd4a00.png)

## Acceptance Criteria

- [x] global achievement button is displayed on every page
- [x] when clicking the button, you should be linked to the achievement page
- [x] when clicking the button on the achievement page you should be linked back to the page where you was before
- [x] for now the achievements are just displayed and you cant unlock them

## Tasks

- [x] create achievement data in a Static JSON
- [x] create achievement page
- [x] create global button
- [x] create an unordered list
- [x] inside the unordered list render as many list items as there are objects in the db.json(use .map)

## Complexity

M
