### ISSUE TITLE
User Story 2: Worldmap button

### ISSUE THREAD

**Issue by Mistake91** [Mistake91/capstone-project#2]
## Value Proposition

**As a User** 
**I want to have a worldmap button**  
**so that i can enter the worldmap from every page** 

## Description

![US2](https://user-images.githubusercontent.com/117996219/213452946-649e1934-66a3-40b4-8232-dd734bd5be37.png)

## Acceptance Criteria

- [x] Global button is displayed on every page
- [x] when clicking the button, you should be linked to the worldmap
- [x] for now there is only the global button displayed on the worldmap page
- [x] when clicking the button on the worldmap you should be linked back to the page where you was before

## Tasks

- [x] create a global button
- [x] create worldmap page
- [x] onClick function for page switch

## Complexity

S

**Comment by ThomasF85** [comment]
Nice small complexity user story!

Is it correct that the worldmap page does not exist after user story #1 and it is a part of this user story to create the worldmap page?
If so: Please describe the worldmap page and its content (even if it is an almost empty page).

Please also clarify what happens if the user clicks the worldmap button on the worldmap page.

**Comment by ThomasF85** [comment]
Looks good!
