### ISSUE TITLE
User Story 10: Unlock achievements

### ISSUE THREAD

**Issue by Mistake91** [Mistake91/capstone-project#20]
## Value Proposition

**As a User**
**I want to be able to unlock achievements**
**so that I can reach my goal to unlock them all** 

## Description

![US10](https://user-images.githubusercontent.com/117996219/215353590-9075b016-aeca-4e2a-a44d-17b909b2fd3f.png)

## Acceptance Criteria

- [x] if all criteria for an achievement are met, the respective achievement should be colored

## Tasks

- [x] expand the local storage so that the amount of the current materials and the all time amount of the materials are stored
- [x] create a function that compares the amount of materials needed for the achievements with the amount of mined materials and colors it if there is a match

## Complexity

M

**Comment by Long-HaHoang** [comment]
Hi Leif,
the scope and complexity is find by me.

Just a side note:
Do mind, if you can capitalize the first letter in your criteria and tasks. Similar to your first task.
