### ISSUE TITLE
User Story 11: Achievement notification

### ISSUE THREAD

**Issue by Mistake91** [Mistake91/capstone-project#21]
## Value Proposition

**As a User** 
**I want to get a notification when unlocking an achievement**
**so that I can see directly when I unlock an achievement** 

## Description

![US11](https://user-images.githubusercontent.com/117996219/215354063-79a2202f-81ae-4ea1-88cf-b63ed4ad1d1c.png)

## Acceptance Criteria

- [x] when unlocking an achievement an popup field should be displayed
- [x] the popup field shows which achievement is unlocked
- [x] when clicking the field, it should disappear again

## Tasks

- [x] expand function from User Story 10 so that a popup field get displayed if the function find a match/when an achievement is unlocked
- [x] onClick function on the popup field so that it disappear

## Complexity

M

**Comment by Long-HaHoang** [comment]
Hi Leif,

you have a typo in the first criteria.
`schould` instead of `should`

I just noticed in your first task you mentioned User Story 10.
I guess the quickest would be to add a link to the story.

P.S.:
- Wait, if you click the popup the it just disappear? No, 30sec ad?

**Comment by Mistake91** [comment]
thanks long, i changed it :)
