### ISSUE TITLE
User Story 12: Smeltery

### ISSUE THREAD

**Issue by Mistake91** [Mistake91/capstone-project#22]
## Value Proposition

**As a User**
**I want to be able to smelt my ores**
**so that I can make ingots for later processing**

## Description

![US12](https://user-images.githubusercontent.com/117996219/215859809-eeb5bea3-8dbe-4d99-a67b-ffde657cdac9.png)

## Acceptance Criteria

- [x] when clicking the smeltery a "which ore you wanna smelt?" popup should be displayed
- [x] on the popup you can choose "iron" or "gold"
- [x] after choosing what you wanna smelt the character starts working
- [x] you shouldn't be able to go lower then 0 and also not higher then the amount of ore and coal you have
- [x] every 3 seconds you get 1 iron ingot and lose 1 iron ore and 1 coal

## Tasks

- [x] change useLocalStorageState from "materials" to "inventar"
- [x] expand useLocalStorageState with "iron ingot" and "gold ingot"
- [x] create a function thats renders a section with h1 and 2 buttons
- [x] after clicking one button the function then checks if you have enough materials
- [x] if you have enough, the crafting starts 
- [x] after a 3 seconds the useLocalStorageState update with the used/lost and new items

## Complexity

L
