### ISSUE TITLE
User Story 13: inventory

### ISSUE THREAD

**Issue by Mistake91** [Mistake91/capstone-project#24]
## Value Proposition

**As a User**
**I want to have an inventory**
**so that I have a better overview of my items**

## Description

![US13](https://user-images.githubusercontent.com/117996219/216027154-93745e72-1e81-4902-8728-8f234f8d23a0.png)

## Acceptance Criteria

- [x] global inventory button should be displayed
- [x] when clicking the button an inventory should be displayed
- [x] all items you own should be displayed
- [x] the amount of each item should be displayed
- [x] an icon for each item should be displayed
      - [ ] for now there are only placeholder icons

## Tasks

- [x] create global button
- [x] create onClick function for the button that renders a section
- [x] create grid template for section
- [x] render each item from local storage into grid fields with placeholder icon 

## Complexity

M-L

**Comment by niklasrammelkamp** [comment]
Nice. I like how you do the wireframes with before and after ! 🥳
