### ISSUE TITLE
User Story 14: market

### ISSUE THREAD

**Issue by Mistake91** [Mistake91/capstone-project#26]
## Value Proposition

**As a User**
**I want to have a market**
**so that I can buy and sell items**

## Description

![US14](https://user-images.githubusercontent.com/117996219/216297422-ebb56859-9a43-47e9-81a6-f70c7eccd6d8.png)

## Acceptance Criteria

- [ ] "market" button is displayed on the worldmap
- [ ] when the user is on the worldmap and click on "market" he should get to the market page
- [ ] for now there is only 1 vendor at the market
- [ ] when clicking the vendor you can choose if you wanna buy or sell
- [ ] for now you can only buy wood sticks
- [ ] if you choose "sell" the inventory will open
- [ ] when you click on an item you get asked how much you wanna sell
- [ ] when selling you lose the amount of items and get the money

## Tasks

- [ ] create button on worldmap
- [ ] onClick function for page switch to the market
- [ ] create market page
- [ ] create button with onClick function that renders 2 buttons
- [ ] "if buy is clicked"
- [ ] render section with 3 buttons with onClick function that updates the local storage
- [ ] "if sale is clicked"
- [ ] map over local storage, each item gets an onClick function
- [ ] onClick function renders 3 buttons with onClick function that updates the local storage

## Complexity

L

**Comment by JoergWolff** [comment]
LGTM
