### ISSUE TITLE
User Story 15: Anvil

### ISSUE THREAD

**Issue by Mistake91** [Mistake91/capstone-project#27]
## Value Proposition

**As a User**
**I want to have an anvil**  
**so that I can process my ingots into high-quality goods**

## Description

![US15](https://user-images.githubusercontent.com/117996219/217120284-26f60e72-6e3b-43e1-b31b-4aa9ea3da824.png)

## Acceptance Criteria

- [x] anvil workstation is displayed on the home page
- [x] when clicking the anvil 2 buttons are displayed
- [x] you can choose if you wanna craft iron gear or gold bracelet
- [x] after choosing:
      - [ ] if you dont have enough materials you get a message
      - [ ] if you have enough, the crafting starts
- [x] after crafting the required materials are removed and the crafted item is added

## Tasks

- [x] add gear and bracelet to local storage
- [x] add workstation component to home page
- [x] create function that renders a section with h1 and 2 buttons
- [x] after clicking one button the function then checks if you have enough materials
- [x] render a message if you dont have enough materials
- [x] if you have enough, the crafting starts
- [x] after 3 seconds the local storage get update with the used/lost and new items

## Complexity

M

**Comment by AstridOttmann** [comment]
Almost got it! :-)
What happens when you don't have enough materials? Do you get a message? What can you do then?
Maybe you can add this.

**Comment by Long-HaHoang** [comment]
Looks good to me.
Just one question you already implemented it in the mining. But happens, when I leave the anvil while crafting.
Does it just cancel the crafting process?
Seems like a similar process to the smelting one.
