### ISSUE TITLE
User Story 16: styling 

### ISSUE THREAD

**Issue by Mistake91** [Mistake91/capstone-project#30]
## Value Proposition

**As a User**
**I want to play a visually appealing game** 
**so that I enjoy spending time playing**

## Description

the whole app is styled with images and styled components

## Acceptance Criteria

- [x] all items, characters, backgrounds buttons etc should get styled with images
- [x] the character should have animation when mining ore or working at home

## Tasks

- [x] import all needed images in images folder
- [x] replace all placeholder images, buttons, etc. with the appropriate images
- [x] if needed, change the placement of some objects

## Complexity

M
