### ISSUE TITLE
User Story 3: Coal mine

### ISSUE THREAD

**Issue by Mistake91** [Mistake91/capstone-project#4]
## Value Proposition

**As a User**
**I want to have a coal mine**
**so that i can mine coal**

## Description

![US3 1](https://user-images.githubusercontent.com/117996219/214016633-7c561659-5694-41de-b544-ff81f1b220ca.png)

## Acceptance Criteria

- [ ] new coal mine page
- [ ] three coal deposits are displayed
- [ ] implement movement function from User Story1

## Tasks

- [ ] create coal mine page
- [ ] create 3 buttons(coal deposits)
- [ ] onClick function to change character position

## Complexity

S
