### ISSUE TITLE
User Story 3: Coal mine

### ISSUE THREAD

**Issue by Mistake91** [Mistake91/capstone-project#5]
## Value Proposition

**As a User**
**I want to have a coal mine**
**so that i can mine coal**

## Description

![US3](https://user-images.githubusercontent.com/117996219/214019089-7cb051b7-d8b3-489e-9cb4-d072c86f2e2e.png)

## Acceptance Criteria

- [x] new coal mine page
- [x] three coal deposits are displayed
- [x] implement movement function from User-Story 1
- [x] create button on worldmap to enter the coal mine

## Tasks

- [x] create coal mine page
- [x] create 3 buttons(coal deposits)
- [x] onClick function to change character position
- [x] create button on worldmap 
- [x] onClick function for page switch to coal mine

## Complexity

M

**Comment by RobinWitt** [comment]
Looks minable to me!
