### ISSUE TITLE
User Story 4: Iron mine

### ISSUE THREAD

**Issue by Mistake91** [Mistake91/capstone-project#7]
## Value Proposition

**As a User**
**I want to have a iron mine**
**so that i can mine iron**

## Description

![US4](https://user-images.githubusercontent.com/117996219/214304803-8a22230c-008b-4923-88a0-6ec072d0a7dc.png)

## Acceptance Criteria

- [x] "iron" button is displayed on the worldmap
- [x] when the user is on the worldmap and click on "iron" he should get to the iron mine page
- [x] three iron deposits are displayed on the iron mine page
- [x] for now there is no "working" function on the deposits

## Tasks

- [x] create iron mine page
- [x]  create 3 buttons(iron deposits)
- [x] implement movement function from User-Story 1
- [x]  onClick function to change character position
- [x]  create button on worldmap
- [x]  onClick function for page switch to iron mine

## Complexity

S

**Comment by mbosselmann** [comment]
Hi Leif,
good job! 👍 I like your user story! But I have some remarks for you for a better understanding of your user story:

**Value proposition**
- this one is fine as for now the user cannot do anything with the iron he is mining :D 

**Description**
- From the wireframes the user flow is not good to understand and should be precised. I have some questions for you that should be answered in your user story:
  - Does the user start from the left screen or from the worldmap? In short: Where is the starting point?
  - Does the user have to click on iron to get to the iron mine page?
  - And is the iron main page the left screen? This should be named somehow. 
- And I would also add "deposit"as name to the iron deposits in your wireframe to mark the deposits
- Maybe you can show the user flow with your wireframes or you can add a description as text to explain it more

**Acceptance criteria & Tasks**
- "implement movement function from User-Story 1" is a task and not an acceptance criterion
- "new iron mine page" if you mean "create a new iron mine page" then this would be a task. But if you mean that the user can go to the iron mine page you should describe in your acceptance criteria how.
- You should also describe in your acceptance criteria what happens when the user enters the iron mine page. For me the production of iron is currently a miracle. 
- There is also no information about how much iron is produced by now or how much the user currently has and should be added as otherwise does not know that something happens when he places his icon on one of the iron deposits or? 🤔 

As you can see I have many questions. 😅
Feel free to ask me if you have further questions!

**Comment by Mistake91** [comment]
Hello Mareike, thanks for your review, i updated my User Story and will post it again and hope all your questions are now answered  😄

**Comment by Mistake91** [comment]
oh yea thank you! i will edit it
