### ISSUE TITLE
User Story 5: Gold mine

### ISSUE THREAD

**Issue by Mistake91** [Mistake91/capstone-project#8]
## Value Proposition

**As a User**
**I want to have a gold mine**
**so that can mine gold**

## Description

![US5](https://user-images.githubusercontent.com/117996219/214282715-fa7538bb-42b6-44d2-94c0-c45631250ab2.png)

## Acceptance Criteria

- [x] "gold" button is displayed on the worldmap
- [x] when the user is on the worldmap and click on "gold" he should get to the gold mine page
- [x] three gold deposits are displayed on the gold mine page
- [x] for now there is no "working" function on the deposits

## Tasks

- [x] create gold mine page
- [x]  create 3 buttons(gold deposits)
- [x] implement movement function from User-Story 1
- [x]  onClick function to change character position
- [x]  create button on worldmap
- [x]  onClick function for page switch to gold mine

## Complexity

S

**Comment by JoergWolff** [comment]
Hey Life LGTM
